ejbca:
  useEphemeralH2Database: false
  env:
    TLS_SETUP_ENABLED: "true"


# The following allows to not use a NodePort and have multiple istances of EJBCA on the same cluster 
services:
  directHttp:
    type: ClusterIP

serviceAccount:
  name: ejbca-init-sa